version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
     - "80:80"
    restart: always
    networks:
     - mynetwork
    depends_on:
     - django

  mysql:
    image: mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test_db
    volumes:
     - /opt/django-mysql:/var/lib/mysql
    networks:
     - mynetwork
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  django:
    build:
      context: .
    container_name: django_cont
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    ports:
     - "8000:8000"
    env_file:
     - ".env"
    restart: always
    networks:
     - mynetwork
    depends_on:
     - mysql
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s



networks:
  mynetwork:
